import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Invoice } from '../types';

export const generateInvoicePDF = (invoice: Invoice) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // Helper to right align text
  const rightText = (text: string, y: number) => {
    doc.text(text, pageWidth - 14, y, { align: 'right' });
  };

  // Header
  doc.setFontSize(22);
  doc.setTextColor(26, 86, 219); // Blue
  doc.text('Gopi Distributors', 14, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text('123, Pharma Market, Sector 5', 14, 26);
  doc.text('Mumbai, Maharashtra - 400001', 14, 31);
  doc.text('GSTIN: 27AAAAA0000A1Z5', 14, 36);
  doc.text('Phone: +91 98765 43210', 14, 41);

  // Invoice Details
  doc.setFontSize(14);
  rightText('TAX INVOICE', 20);
  doc.setFontSize(10);
  rightText(`Invoice No: ${invoice.invoiceNo}`, 26);
  rightText(`Date: ${new Date(invoice.date).toLocaleDateString()}`, 31);

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(14, 45, 196, 45);

  // Bill To
  doc.setFontSize(11);
  doc.text('Bill To:', 14, 52);
  doc.setFontSize(10);
  doc.text(invoice.partyName, 14, 58);
  doc.text(invoice.partyAddress, 14, 63);
  doc.text(`GSTIN: ${invoice.partyGstin}`, 14, 68);

  // Table
  const tableColumn = ["SN", "Item", "HSN", "Batch", "Exp", "Qty", "Rate", "Disc%", "Taxable", "GST%", "Amount"];
  const tableRows: any[] = [];

  invoice.items.forEach((item, index) => {
    const totalGSTPercent = item.gstRate;
    const amount = item.totalAmount;
    
    const row = [
      index + 1,
      item.name,
      item.hsn,
      item.batch,
      item.expiry,
      item.quantity,
      item.saleRate.toFixed(2),
      item.discountPercent,
      item.taxableValue.toFixed(2),
      `${totalGSTPercent}%`,
      amount.toFixed(2),
    ];
    tableRows.push(row);
  });

  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 75,
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [26, 86, 219], textColor: [255, 255, 255] },
    columnStyles: {
      0: { cellWidth: 8 },
      1: { cellWidth: 'auto' }, // Item name
      5: { halign: 'center' },
      6: { halign: 'right' },
      8: { halign: 'right' },
      10: { halign: 'right' },
    }
  });

  // Totals
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  
  doc.setFontSize(9);
  
  // Tax breakdown
  const taxX = 14;
  doc.text('Tax Breakdown:', taxX, finalY);
  doc.text(`Total Taxable Value: ${invoice.totalTaxable.toFixed(2)}`, taxX, finalY + 5);
  doc.text(`CGST: ${invoice.totalCGST.toFixed(2)}`, taxX, finalY + 10);
  doc.text(`SGST: ${invoice.totalSGST.toFixed(2)}`, taxX, finalY + 15);
  doc.text(`IGST: ${invoice.totalIGST.toFixed(2)}`, taxX, finalY + 20);

  // Grand Total Box
  const totalBoxX = 120;
  const totalBoxY = finalY - 2;
  doc.setFillColor(241, 245, 249);
  doc.rect(totalBoxX, totalBoxY, 76, 25, 'F');
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Grand Total: ₹${invoice.grandTotal.toFixed(2)}`, totalBoxX + 5, totalBoxY + 16);

  // Footer Terms
  doc.setFontSize(8);
  doc.setTextColor(100);
  const pageHeight = doc.internal.pageSize.height;
  doc.text('Terms & Conditions:', 14, pageHeight - 30);
  doc.text('1. Goods once sold will not be taken back.', 14, pageHeight - 25);
  doc.text('2. Interest @18% p.a. will be charged if payment is not made within due date.', 14, pageHeight - 21);
  doc.text('3. All disputes subject to Mumbai Jurisdiction.', 14, pageHeight - 17);

  // Footer Credit
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by Gopi Distributors Billing System', 14, pageHeight - 10);
  doc.text('Created By Yash K Pathak', pageWidth - 14, pageHeight - 10, { align: 'right' });

  doc.save(`Invoice_${invoice.invoiceNo}.pdf`);
};