import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Invoice } from '../types';
import { db } from '../db';

export const generateInvoicePDF = async (invoice: Invoice) => {
  const profile = await db.settings.get(1);
  const companyName = profile?.companyName || 'Gopi Distributors';
  const address1 = profile?.addressLine1 || 'Address Line 1';
  const address2 = profile?.addressLine2 || 'City, State - Zip';
  const gstin = profile?.gstin || '27AAAAA0000A1Z5';
  const dl1 = profile?.dlNo1 || '';
  const dl2 = profile?.dlNo2 || '';
  const phone = profile?.phone || '';
  const terms = profile?.terms?.split('\n') || ['Goods once sold will not be taken back.'];

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // Helper to right align text
  const rightText = (text: string, y: number) => {
    doc.text(text, pageWidth - 14, y, { align: 'right' });
  };

  // Header
  doc.setFontSize(22);
  doc.setTextColor(26, 86, 219); // Blue
  doc.text(companyName, 14, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text(address1, 14, 26);
  doc.text(address2, 14, 31);
  
  let currentY = 36;
  doc.text(`GSTIN: ${gstin}`, 14, currentY);
  currentY += 5;
  
  if (dl1 || dl2) {
    const dlText = [dl1 ? `DL 1: ${dl1}` : '', dl2 ? `DL 2: ${dl2}` : ''].filter(Boolean).join(' | ');
    doc.text(dlText, 14, currentY);
    currentY += 5;
  }

  if(phone) doc.text(`Phone: ${phone}`, 14, currentY);

  // Invoice Details
  doc.setFontSize(14);
  rightText('TAX INVOICE', 20);
  doc.setFontSize(10);
  rightText(`Invoice No: ${invoice.invoiceNo}`, 26);
  rightText(`Date: ${new Date(invoice.date).toLocaleDateString()}`, 31);

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(14, 48, 196, 48);

  // Bill To
  doc.setFontSize(11);
  doc.text('Bill To:', 14, 55);
  doc.setFontSize(10);
  doc.text(invoice.partyName, 14, 61);
  doc.text(invoice.partyAddress, 14, 66);
  doc.text(`GSTIN: ${invoice.partyGstin}`, 14, 71);

  // Table
  const tableColumn = ["SN", "Item", "HSN", "Batch", "Exp", "Qty", "Rate", "Disc%", "Taxable", "GST%", "Amount"];
  const tableRows: any[] = [];

  invoice.items.forEach((item, index) => {
    const totalGSTPercent = item.gstRate;
    const amount = item.totalAmount;
    
    const row = [
      index + 1,
      item.name,
      item.hsn,
      item.batch,
      item.expiry,
      item.quantity,
      item.saleRate.toFixed(2),
      item.discountPercent,
      item.taxableValue.toFixed(2),
      `${totalGSTPercent}%`,
      amount.toFixed(2),
    ];
    tableRows.push(row);
  });

  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 78,
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [26, 86, 219], textColor: [255, 255, 255] },
    columnStyles: {
      0: { cellWidth: 8 },
      1: { cellWidth: 'auto' }, // Item name
      5: { halign: 'center' },
      6: { halign: 'right' },
      8: { halign: 'right' },
      10: { halign: 'right' },
    }
  });

  // Totals
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  
  doc.setFontSize(9);
  
  // Tax breakdown
  const taxX = 14;
  doc.text('Tax Breakdown:', taxX, finalY);
  doc.text(`Total Taxable Value: ${invoice.totalTaxable.toFixed(2)}`, taxX, finalY + 5);
  doc.text(`CGST: ${invoice.totalCGST.toFixed(2)}`, taxX, finalY + 10);
  doc.text(`SGST: ${invoice.totalSGST.toFixed(2)}`, taxX, finalY + 15);
  doc.text(`IGST: ${invoice.totalIGST.toFixed(2)}`, taxX, finalY + 20);

  // Grand Total Box
  const totalBoxX = 120;
  const totalBoxY = finalY - 2;
  doc.setFillColor(241, 245, 249);
  doc.rect(totalBoxX, totalBoxY, 76, 25, 'F');
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Grand Total: ₹${invoice.grandTotal.toFixed(2)}`, totalBoxX + 5, totalBoxY + 16);

  // Footer Terms
  doc.setFontSize(8);
  doc.setTextColor(100);
  const pageHeight = doc.internal.pageSize.height;
  doc.text('Terms & Conditions:', 14, pageHeight - 35);
  
  let termY = pageHeight - 30;
  terms.forEach((term) => {
      doc.text(term, 14, termY);
      termY += 4;
  });

  // Footer Credit
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(`Generated by ${companyName} Billing System`, 14, pageHeight - 10);
  doc.text('Created By Yash K Pathak', pageWidth - 14, pageHeight - 10, { align: 'right' });

  doc.save(`Invoice_${invoice.invoiceNo}.pdf`);
};